# Generated by Django 5.0.6 on 2024-12-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastprices',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
