# Generated by Django 5.0.6 on 2024-12-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_pastprices_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='hi', max_length=500),
            preserve_default=False,
        ),
    ]
